#!/usr/bin/env python3
# release.py - Build a deployable artifact for the clean rebuild
# Copyright (c) 2026 dodson Software ( dodson labs )
# SPDX-License-Identifier: MIT

import io
import pathlib
import subprocess
import sys
import tarfile
import time
from version import FIRMWARE_VERSION

ROOT = pathlib.Path(__file__).resolve().parent

# Required files for deployment (Python files and config)
REQUIRED_FILES = {
    "main.py",
    "core0.py",
    "core1.py",
    "config.py",
    "intercore.py",
    "message_protocol.py",
    "message_serializer.py",
    "wifi.py",
    "mqtt.py",
    "mqtt_client.py",
    "network_diagnostics.py",
    "system_information.py",
    "uptime.py",
    "device_manager.py",
    "device_factory.py",
    "led_manager.py",
    "debug.py",
    "version.py",
    "hardware.py",
    "observability.py",
}

# Optional files (config files, user-provided)
OPTIONAL_FILES = {
    "config.json",
}

# Required package files (directories with __init__.py)
REQUIRED_PACKAGES = {
    "devices/__init__.py",
    "devices/device.py",
    "devices/system_information/__init__.py",
    "devices/system_information/system_information_device.py",
}

FILES = REQUIRED_FILES | OPTIONAL_FILES | REQUIRED_PACKAGES

# Build identity: the commit identifies HEAD only. A dirty working tree does
# not change release policy (it neither blocks a release nor adds a marker) --
# and a failed lookup degrades to "unknown" rather than failing the release.
BUILD_COMMIT_FALLBACK = "unknown"
BUILD_COMMIT_MIN_LENGTH = 7


def resolve_build_commit(root=None):
    """Resolve the short commit SHA this build is released from.

    Host-side only: the Pico never runs git. ``git rev-parse --short HEAD``
    is the single source. Any failure -- no git binary, not a repository,
    no HEAD, a non-hex or too-short result -- degrades to BUILD_COMMIT_FALLBACK
    so a release can still be built (the firmware's dev fallback is the same
    value, so the archive and the source tree agree).

    Args:
        root: repository directory (defaults to this file's directory)

    Returns:
        a short commit SHA (at least BUILD_COMMIT_MIN_LENGTH hex chars),
        or BUILD_COMMIT_FALLBACK
    """
    cwd = str(root) if root is not None else str(ROOT)
    try:
        result = subprocess.run(
            ["git", "rev-parse", "--short", "HEAD"],
            cwd=cwd,
            capture_output=True,
            text=True,
            timeout=10,
        )
    except Exception:
        return BUILD_COMMIT_FALLBACK
    if result.returncode != 0:
        return BUILD_COMMIT_FALLBACK
    commit = result.stdout.strip()
    if len(commit) < BUILD_COMMIT_MIN_LENGTH:
        return BUILD_COMMIT_FALLBACK
    if not all(c in "0123456789abcdef" for c in commit.lower()):
        return BUILD_COMMIT_FALLBACK
    return commit


def build_info_module_content(commit):
    """Build the generated build_info.py module content for a commit."""
    return (
        "# build_info.py - Generated by release.py; do not edit by hand.\n"
        "# Copyright (c) 2026 dodson Software ( dodson labs )\n"
        "# SPDX-License-Identifier: MIT\n"
        "#\n"
        "# Build identity: the short commit SHA this release was built from\n"
        "# (host-side git at release time; the Pico never runs git).\n"
        "\n"
        "FIRMWARE_BUILD_COMMIT = \"{}\"\n".format(commit)
    )


def add_build_info_to_archive(archive, content):
    """Add the generated build_info.py module to a release archive.

    build_info.py is generated for the release -- it is deliberately NOT in
    REQUIRED_FILES, because the working tree must not carry a stale copy of
    another commit's identity.
    """
    encoded = content.encode("utf-8")
    info = tarfile.TarInfo("build_info.py")
    info.size = len(encoded)
    info.mtime = int(time.time())
    info.mode = 0o644
    archive.addfile(info, io.BytesIO(encoded))


def verify_build_info_in_archive(artifact, content):
    """Reopen the written archive and verify build_info.py's presence and
    exact content (the archive must not drift from what was generated, and
    nothing else may supply the build identity)."""
    with tarfile.open(artifact, "r:gz") as archive:
        names = archive.getnames()
        if "build_info.py" not in names:
            raise SystemExit("Release archive is missing build_info.py")
        stored = archive.extractfile("build_info.py").read().decode("utf-8")
        if stored != content:
            raise SystemExit("build_info.py content in the archive does not match the generated content")


def build_artifact(output_dir):
    """Build the release archive into output_dir and return its path."""
    output_dir = pathlib.Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    artifact = output_dir / "sensor-firmware-{}.tar.gz".format(FIRMWARE_VERSION)

    build_commit = resolve_build_commit()
    build_info_content = build_info_module_content(build_commit)

    with tarfile.open(artifact, "w:gz") as archive:
        for name in FILES:
            path = ROOT / name
            if not path.exists():
                raise SystemExit("Missing required file: {}".format(name))
            archive.add(path, arcname=name)
        add_build_info_to_archive(archive, build_info_content)

    verify_build_info_in_archive(artifact, build_info_content)
    print("FIRMWARE_BUILD_COMMIT: {}".format(build_commit))
    return artifact


def main():
    if len(sys.argv) > 2:
        raise SystemExit("Usage: python3 release.py [OUTPUT_DIR]")
    output_dir = pathlib.Path(sys.argv[1]) if len(sys.argv) == 2 else ROOT / "releases"
    artifact = build_artifact(output_dir)
    print("Artifact: {}".format(artifact))


if __name__ == "__main__":
    main()
